name: latticerl
channels:
  - defaults
dependencies:
  - cycler
  - google-auth-oauthlib
  - future
  - libiconv
  - pyasn1-modules
  - zstd
  - parso
  - mccabe
  - pyzmq
  - libva
  - dataclasses
  - astroid
  - tomli
  - wheel
  - idna
  - aom
  - mypy_extensions
  - xorg-kbproto
  - brotli-bin
  - libpng
  - libprotobuf
  - yarl
  - urllib3
  - libblas
  - libnsl
  - cloudpickle
  - jupyter_core
  - importlib-metadata
  - python=3.9
  - ca-certificates
  - wcwidth
  - pyparsing
  - bzip2
  - frozenlist
  - unicodedata2
  - libgfortran-ng
  - freetype
  - xorg-libx11
  - setuptools
  - tensorboard
  - pexpect
  - tensorboard-plugin-wit
  - libcblas
  - tk
  - python-dateutil
  - certifi
  - jedi
  - libwebp-base
  - pyu2f
  - libbrotlidec
  - libpciaccess
  - xorg-libxfixes
  - six
  - pyjwt
  - pyopenssl
  - jbig
  - pandas
  - grpcio
  - ninja
  - svt-av1
  - libbrotlienc
  - isort
  - wrapt
  - protobuf
  - click
  - rsa
  - pyglet
  - python_abi
  - google-auth
  - xz
  - libtiff
  - attrs
  - traitlets
  - backcall
  - ipython
  - requests
  - typed-ast
  - zipp
  - x264
  - stable-baselines3
  - munkres
  - jpeg
  - decorator
  - pip
  - openh264
  - zeromq
  - entrypoints
  - cachetools
  - xorg-libxau
  - pysocks
  - lerc
  - packaging
  - libvpx
  - pthread-stubs
  - asttokens
  - libxcb
  - pickleshare
  - werkzeug
  - aiosignal
  - mkl
  - llvm-openmp
  - ffmpeg
  - prompt-toolkit
  - xorg-libxdmcp
  - gmp
  - ncurses
  - numpy
  - pure_eval
  - libzlib
  - xorg-libxext
  - _libgcc_mutex
  - libdeflate
  - libstdcxx-ng
  - sleef
  - libgcc-ng
  - nest-asyncio
  - zlib
  - gnutls
  - xorg-xextproto
  - ld_impl_linux-64
  - tzdata
  - libxml2
  - libgfortran5
  - pytorch
  - libdrm
  - backports
  - ipykernel
  - black
  - jupyter_client
  - libbrotlicommon
  - openjpeg
  - stack_data
  - aiohttp
  - blinker
  - typing-extensions
  - brotlipy
  - libsodium
  - gym
  - pytz
  - multidict
  - tornado
  - brotli
  - cryptography
  - x265
  - absl-py
  - debugpy
  - xorg-fixesproto
  - pycparser
  - typing_extensions
  - platformdirs
  - xorg-xproto
  - libffi
  - cffi
  - lame
  - backports.functools_lru_cache
  - lz4-c
  - toml
  - nettle
  - libuuid
  - icu
  - async-timeout
  - markdown
  - pathspec
  - matplotlib-inline
  - pygments
  - pylint
  - liblapack
  - readline
  - tbb
  - _openmp_mutex
  - pillow
  - ptyprocess
  - executing
  - kiwisolver
  - sqlite
  - colorama
  - lazy-object-proxy
  - c-ares
  - requests-oauthlib
  - fonttools
  - tensorboard-data-server
  - giflib
  - libwebp
  - oauthlib
  - charset-normalizer
  - openssl
  - lcms2
  - scipy
  - pyasn1
  - cudatoolkit
  - seaborn
  - mypy
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - notebook
